name: location_windows
description: Windows implementation of the location plugin
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

flutter:
  plugin:
    implements: location
    platforms:
      windows:
        pluginClass: LocationWindows
        dartPluginClass: LocationWindows

dependencies:
  flutter:
    sdk: flutter
  location_platform_interface:
    path: ../location_platform_interface

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^3.0.0
