name: location_web
description: Web implementation of the location plugin
version: 5.0.0-dev.0

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

flutter:
  plugin:
    implements: location
    platforms:
      web:
        pluginClass: LocationWeb
        fileName: location_web.dart

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  location_platform_interface:
    path: ../location_platform_interface

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^3.0.0
